In [1]:
# =====================================================================
# 1. Conecta a OneLake y lee la tabla mensual de silver.
# =====================================================================
try:
    from deltalake import DeltaTable
except ModuleNotFoundError:
    import sys, subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "deltalake"])
    from deltalake import DeltaTable

from msal import ConfidentialClientApplication
import pandas as pd
import numpy as np

TENANT_ID     = "a8571760-3e06-487e-957e-e38e27254e02"
CLIENT_ID     = "30df81e6-980d-4a53-bf84-27a0b0c6338e"
CLIENT_SECRET = "IGN8Q~FwgNgc9UO7~zKIQ-2HVWVPQtjYn6khUajb"

FABRIC_WORKSPACE_ID = "1a3256b7-8ccf-4be6-88d0-f0338b57c58c"
LAKEHOUSE_ID        = "49804c1d-ae26-4818-beaf-0d5c96796119"

app = ConfidentialClientApplication(
    client_id=CLIENT_ID,
    authority=f"https://login.microsoftonline.com/{TENANT_ID}",
    client_credential=CLIENT_SECRET
)

result = app.acquire_token_for_client(
    scopes=["https://onelake.fabric.microsoft.com/.default"]
)

if "access_token" not in result:
    raise Exception(result.get("error_description", result))

ruta = (
    f"abfss://{FABRIC_WORKSPACE_ID}@onelake.dfs.fabric.microsoft.com/"
    f"{LAKEHOUSE_ID}/Files/"
    f"TP_MSPLogistica_Lakehouse/"
    f"silver/indicadores_cluster_features"
)

df = DeltaTable(
    ruta,
    storage_options={"bearer_token": result["access_token"],
                     "use_fabric_endpoint": "true"}
).to_pandas()

print("Filas:   ", df.shape[0], "  (esperado 30,203)")
print("Columnas:", df.shape[1])

Filas:    30203   (esperado 30,203)
Columnas: 91

In [2]:
# =====================================================================
# 2. Corrige la base de usuarios y verifica el resultado.
#
# La columna BaseDeUsuarios no guarda el cierre del mes: guarda la suma
# de los cortes semanales, que se hacen en domingo. Un mes de 5 domingos
# trae 5 sumados. Por eso se divide entre los domingos que tuvo el mes.
# =====================================================================
MES_INCOMPLETO = 202608   # solo alcanzo un corte de cinco, se excluye

df["Fecha"] = pd.to_datetime(df["Fecha"])

meses = df[["AnioMes", "Fecha"]].drop_duplicates("AnioMes").copy()
meses["DomingosDelMes"] = meses["Fecha"].apply(
    lambda f: len(pd.date_range(f.replace(day=1),
                                f.replace(day=1) + pd.offsets.MonthEnd(0),
                                freq="W-SUN"))
)

df = df.merge(meses[["AnioMes", "DomingosDelMes"]], on="AnioMes", how="left")
df["BaseReal"] = df["BaseDeUsuarios"] / df["DomingosDelMes"]

verificacion = (df[df["AnioMes"] != MES_INCOMPLETO]
                .groupby(["AnioMes", "DomingosDelMes"], as_index=False)
                .agg(BasePublicada=("BaseDeUsuarios", "sum"),
                     BaseReal=("BaseReal", "sum"),
                     Bajas=("Cancelaciones", lambda s: s.abs().sum())))

verificacion["ChurnPublicado"] = (100 * verificacion["Bajas"]
                                  / (verificacion["BasePublicada"] / 4.3333333)).round(3)
verificacion["ChurnCorregido"] = (100 * verificacion["Bajas"]
                                  / verificacion["BaseReal"]).round(3)
verificacion["BaseReal"] = verificacion["BaseReal"].round(0)

print("La base corregida debe crecer pareja de 5.16 a 5.64 millones.")
print("La publicada brinca porque suma cortes.")
verificacion

La base corregida debe crecer pareja de 5.16 a 5.64 millones.
La publicada brinca porque suma cortes.

,AnioMes,DomingosDelMes,BasePublicada,BaseReal,Bajas,ChurnPublicado,ChurnCorregido
0,202501,4,20662561,5165640.0,87594,1.837,1.696
1,202502,4,20790135,5197534.0,71170,1.483,1.369
2,202503,5,26167283,5233457.0,71254,1.180,1.362
3,202504,4,21045494,5261374.0,92831,1.911,1.764
4,202505,4,21052382,5263096.0,101078,2.081,1.921
5,202506,5,26312720,5262544.0,70872,1.167,1.347
6,202507,4,21200657,5300164.0,107970,2.207,2.037
7,202508,5,26520003,5304001.0,96520,1.577,1.820
8,202509,4,21279120,5319780.0,89375,1.820,1.680
9,202510,4,21296801,5324200.0,94231,1.917,1.770
10,202511,5,26635851,5327170.0,86709,1.411,1.628
11,202512,4,21473144,5368286.0,85324,1.722,1.589
12,202601,4,21583608,5395902.0,86240,1.731,1.598
13,202602,4,21711066,5427766.0,82304,1.643,1.516
14,202603,5,27304220,5460844.0,90751,1.440,1.662
15,202604,4,22044314,5511078.0,82285,1.618,1.493
16,202605,5,27716928,5543386.0,86907,1.359,1.568
17,202606,4,22381285,5595321.0,86377,1.672,1.544
18,202607,4,22552852,5638213.0,86648,1.665,1.537

In [3]:
# =====================================================================
# 3. Construye la tabla de entrenamiento con las tres definiciones de churn.
# =====================================================================
DEFINICIONES = [("Bajas totales",  "Cancelaciones"),
                ("Voluntarias",    "CancelacionesVoluntarias"),
                ("Involuntarias",  "CancelacionesInvoluntarias")]

base = df[(df["AnioMes"] != MES_INCOMPLETO) & (df["BaseReal"] > 0)].copy()

partes = []
for nombre, columna in DEFINICIONES:
    p = base[["Cluster", "AnioMes", "Mes", "Trimestre",
              "Instalaciones", "BaseReal"]].copy()
    p["Definicion"] = nombre
    p["Bajas"] = base[columna].abs()
    partes.append(p)

largo = pd.concat(partes, ignore_index=True)
largo["Churn"] = 100.0 * largo["Bajas"] / largo["BaseReal"]

largo = largo.sort_values(["Definicion", "Cluster", "AnioMes"])
g = largo.groupby(["Definicion", "Cluster"])

# Lo que hay que predecir: churn a uno, dos y tres meses
largo["Churn_T1"] = g["Churn"].shift(-1)
largo["Churn_T2"] = g["Churn"].shift(-2)
largo["Churn_T3"] = g["Churn"].shift(-3)

# Historia del churn
largo["Churn_M1"] = g["Churn"].shift(1)
largo["Churn_M2"] = g["Churn"].shift(2)
largo["Churn_M3"] = g["Churn"].shift(3)
largo["Churn_Prom3M"] = g["Churn"].transform(lambda s: s.shift(1).rolling(3).mean())
largo["Churn_Prom6M"] = g["Churn"].transform(lambda s: s.shift(1).rolling(6).mean())
largo["Churn_Delta1M"] = g["Churn"].shift(1) - g["Churn"].shift(2)
largo["Churn_Delta3M"] = g["Churn"].shift(1) - g["Churn"].shift(4)
largo["Churn_Delta6M"] = g["Churn"].shift(1) - g["Churn"].shift(7)

# Tamano, crecimiento y actividad comercial de la zona
largo["Base_M1"] = g["BaseReal"].shift(1)
base_m2 = g["BaseReal"].shift(2)
largo["Base_Crecimiento1M"] = 100.0 * (largo["Base_M1"] - base_m2) / base_m2
largo["Bajas_M1"] = g["Bajas"].shift(1)
largo["Instalaciones_M1"] = g["Instalaciones"].shift(1)

VARIABLES = ["Churn", "Churn_M1", "Churn_M2", "Churn_M3",
             "Churn_Prom3M", "Churn_Prom6M",
             "Churn_Delta1M", "Churn_Delta3M", "Churn_Delta6M",
             "Base_M1", "Base_Crecimiento1M", "Bajas_M1", "Instalaciones_M1",
             "Mes", "Trimestre"]

print("Renglones:", len(largo), "  (esperado 85,962)")
largo.groupby("Definicion").agg(
    Renglones=("Churn", "size"),
    ChurnPromedio=("Churn", "mean"),
    UtilesT1=("Churn_T1", lambda s: s.notna().sum())
).round(3)

Renglones: 85962   (esperado 85,962)

               Renglones  ChurnPromedio  UtilesT1
Definicion
Bajas totales      28654          1.710     27145
Involuntarias      28654          1.244     27145
Voluntarias        28654          0.466     27145

In [4]:
# =====================================================================
# 4. Justifica el piso minimo de clientes.
#
# Las zonas con muy pocos clientes hacen que el churn como porcentaje
# no sea medible: con 4 clientes, uno que se va son 25 puntos. Aqui se
# mide cuanto pesan esas zonas y cuanto mejora el error al excluirlas,
# comparando siempre contra el pronostico ingenuo para que sea parejo.
# =====================================================================
from sklearn.ensemble import RandomForestRegressor

MES_CORTE  = 202603
MESES_TEST = [202604, 202605, 202606]
PISOS      = [0, 50, 100, 200, 500, 1000]

d = largo[largo["Definicion"] == "Bajas totales"].dropna(
    subset=VARIABLES + ["Churn_T1"])

ent = d[d["AnioMes"] <= MES_CORTE]
val = d[d["AnioMes"].isin(MESES_TEST)].copy()

m = RandomForestRegressor(n_estimators=100, max_depth=8,
                          random_state=42, n_jobs=-1)
m.fit(ent[VARIABLES], ent["Churn_T1"])

val["Pronostico"]   = m.predict(val[VARIABLES])
val["ErrorModelo"]  = (val["Churn_T1"] - val["Pronostico"]).abs()
val["ErrorIngenuo"] = (val["Churn_T1"] - val["Churn"]).abs()

filas = []
for piso in PISOS:
    v = val[val["Base_M1"] >= piso]
    total = v["Churn_T1"].sum()
    err_ing = 100 * v["ErrorIngenuo"].sum() / total
    err_mod = 100 * v["ErrorModelo"].sum() / total
    filas.append({
        "PisoDeClientes": piso,
        "Zonas": v["Cluster"].nunique(),
        "PctDeLaBase": round(100 * v["Base_M1"].sum() / val["Base_M1"].sum(), 2),
        "ErrorSinModelo": round(err_ing, 2),
        "ErrorConModelo": round(err_mod, 2),
        "Mejora": round(100 * (err_ing - err_mod) / err_ing, 1),
        "MAE": round(v["ErrorModelo"].mean(), 3),
    })

print("Con piso de 100 se conserva mas del 99.8% de la base.")
pd.DataFrame(filas)

Con piso de 100 se conserva mas del 99.8% de la base.

,PisoDeClientes,Zonas,PctDeLaBase,ErrorSinModelo,ErrorConModelo,Mejora,MAE
0,0,1509,100.00,41.42,35.17,15.1,0.585
1,50,1394,99.95,32.89,26.70,18.8,0.442
2,100,1309,99.84,28.50,23.21,18.6,0.386
3,200,1172,99.47,23.81,19.84,16.7,0.331
4,500,968,98.23,18.49,15.61,15.6,0.256
5,1000,791,95.98,15.22,13.35,12.3,0.216

In [5]:
# =====================================================================
# 5. Entrena los nueve modelos con el piso aplicado.
#
# Cada horizonte usa un corte distinto para que los tres pronostiquen
# los mismos meses: mayo, junio y julio de 2026.
# =====================================================================
PISO = 100

CORTE  = {1: 202603, 2: 202602, 3: 202601}
VALIDA = {1: [202604, 202605, 202606],
          2: [202603, 202604, 202605],
          3: [202602, 202603, 202604]}

resultados = []
modelos = {}

for definicion, _ in DEFINICIONES:
    for h in [1, 2, 3]:
        objetivo = f"Churn_T{h}"

        d = largo[(largo["Definicion"] == definicion) &
                  (largo["Base_M1"] >= PISO)].dropna(
            subset=VARIABLES + [objetivo])

        ent = d[d["AnioMes"] <= CORTE[h]]
        val = d[d["AnioMes"].isin(VALIDA[h])]

        m = RandomForestRegressor(n_estimators=100, max_depth=8,
                                  random_state=42, n_jobs=-1)
        m.fit(ent[VARIABLES], ent[objetivo])
        modelos[(definicion, h)] = m

        pred    = m.predict(val[VARIABLES])
        real    = val[objetivo].values
        ingenuo = val["Churn"].values

        err_mod = np.abs(real - pred).sum()
        err_ing = np.abs(real - ingenuo).sum()
        total   = real.sum()

        resultados.append({
            "Definicion": definicion,
            "Horizonte": f"T{h}",
            "ChurnReal": round(real.mean(), 3),
            "ErrorSinModelo": round(100 * err_ing / total, 2),
            "ErrorConModelo": round(100 * err_mod / total, 2),
            "Mejora": round(100 * (err_ing - err_mod) / err_ing, 1),
            "LeGana": "SI" if err_mod < err_ing else "NO",
            "MAE": round(np.abs(real - pred).mean(), 3),
            "Entrenamiento": len(ent),
            "Prueba": len(val),
        })
        print("listo:", definicion, f"T{h}")

pd.DataFrame(resultados)

listo: Bajas totales T1
listo: Bajas totales T2
listo: Bajas totales T3
listo: Voluntarias T1
listo: Voluntarias T2
listo: Voluntarias T3
listo: Involuntarias T1
listo: Involuntarias T2
listo: Involuntarias T3

,Definicion,Horizonte,ChurnReal,ErrorSinModelo,ErrorConModelo,Mejora,LeGana,MAE,Entrenamiento,Prueba
0,Bajas totales,T1,1.665,28.50,23.03,19.2,SI,0.383,10327,3919
1,Bajas totales,T2,1.665,30.69,24.01,21.7,SI,0.400,9025,3914
2,Bajas totales,T3,1.665,31.50,24.10,23.5,SI,0.401,7723,3908
3,Voluntarias,T1,0.382,53.44,46.29,13.4,SI,0.177,10327,3919
4,Voluntarias,T2,0.382,56.37,46.94,16.7,SI,0.179,9025,3914
5,Voluntarias,T3,0.381,57.59,47.20,18.0,SI,0.180,7723,3908
6,Involuntarias,T1,1.284,32.29,26.49,18.0,SI,0.340,10327,3919
7,Involuntarias,T2,1.284,34.69,27.58,20.5,SI,0.354,9025,3914
8,Involuntarias,T3,1.284,36.15,27.42,24.2,SI,0.352,7723,3908

In [6]:
# =====================================================================
# 6. Pronostico real de agosto, septiembre y octubre de 2026.
#
# Aqui ya no se esconde nada: se entrena con toda la historia disponible
# y se pronostican meses que todavia no ocurren.
# =====================================================================
ULTIMO_MES = 202607
MES_NOMBRE = {1: "agosto 2026", 2: "septiembre 2026", 3: "octubre 2026"}

pronostico = []

for definicion, _ in DEFINICIONES:
    for h in [1, 2, 3]:
        objetivo = f"Churn_T{h}"

        d = largo[(largo["Definicion"] == definicion) &
                  (largo["Base_M1"] >= PISO)]

        ent = d.dropna(subset=VARIABLES + [objetivo])
        hoy = d[d["AnioMes"] == ULTIMO_MES].dropna(subset=VARIABLES)

        m = RandomForestRegressor(n_estimators=100, max_depth=8,
                                  random_state=42, n_jobs=-1)
        m.fit(ent[VARIABLES], ent[objetivo])

        pred = m.predict(hoy[VARIABLES])
        peso = hoy["BaseReal"].values

        pronostico.append({
            "Definicion": definicion,
            "MesPronosticado": MES_NOMBRE[h],
            "ChurnPronosticadoPct": round(float(np.average(pred, weights=peso)), 3),
            "ZonasPronosticadas": len(hoy),
            "ClientesCubiertos": round(peso.sum()),
        })
        print("listo:", definicion, MES_NOMBRE[h])

print()
print("Referencia: el churn de julio 2026 fue 1.537%")
pd.DataFrame(pronostico)

listo: Bajas totales agosto 2026
listo: Bajas totales septiembre 2026
listo: Bajas totales octubre 2026
listo: Voluntarias agosto 2026
listo: Voluntarias septiembre 2026
listo: Voluntarias octubre 2026
listo: Involuntarias agosto 2026
listo: Involuntarias septiembre 2026
listo: Involuntarias octubre 2026

Referencia: el churn de julio 2026 fue 1.537%

,Definicion,MesPronosticado,ChurnPronosticadoPct,ZonasPronosticadas,ClientesCubiertos
0,Bajas totales,agosto 2026,1.521,1308,5628965
1,Bajas totales,septiembre 2026,1.516,1308,5628965
2,Bajas totales,octubre 2026,1.494,1308,5628965
3,Voluntarias,agosto 2026,0.376,1308,5628965
4,Voluntarias,septiembre 2026,0.373,1308,5628965
5,Voluntarias,octubre 2026,0.366,1308,5628965
6,Involuntarias,agosto 2026,1.145,1308,5628965
7,Involuntarias,septiembre 2026,1.145,1308,5628965
8,Involuntarias,octubre 2026,1.161,1308,5628965

In [7]:
# =====================================================================
# 7. Registra los Data Assets con el piso aplicado, para correr AutoML.
#
# Version 2 porque la 1 se subio sin piso. Los Data Assets son inmutables:
# si la version ya existe, no se toca.
# =====================================================================
try:
    import mltable
    from azure.ai.ml import MLClient
    from azure.ai.ml.entities import Data
    from azure.ai.ml.constants import AssetTypes
    from azure.identity import DefaultAzureCredential
except ModuleNotFoundError:
    import sys, subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q",
                           "mltable", "azure-ai-ml", "azure-identity"])
    import mltable
    from azure.ai.ml import MLClient
    from azure.ai.ml.entities import Data
    from azure.ai.ml.constants import AssetTypes
    from azure.identity import DefaultAzureCredential

import os

ASSET_TRAIN   = "CHURN_REG_T1_V02_TRAIN"
ASSET_TEST    = "CHURN_REG_T1_V02_TEST"
ASSET_VERSION = "1"

DEFINICION = "Bajas totales"
OBJETIVO   = "Churn_T1"

d = largo[(largo["Definicion"] == DEFINICION) &
          (largo["Base_M1"] >= PISO)].dropna(subset=VARIABLES + [OBJETIVO])

conjuntos = {
    ASSET_TRAIN: d[d["AnioMes"] <= MES_CORTE],
    ASSET_TEST:  d[d["AnioMes"].isin(MESES_TEST)],
}

cliente = MLClient.from_config(credential=DefaultAzureCredential())

for nombre, tabla in conjuntos.items():
    try:
        existente = cliente.data.get(name=nombre, version=ASSET_VERSION)
        print(nombre, "- ya existe la version", existente.version, "- se omite")
        continue
    except Exception:
        pass

    carpeta = f"./assets/{nombre}"
    os.makedirs(carpeta, exist_ok=True)

    tabla[VARIABLES + [OBJETIVO]].to_parquet(
        f"{carpeta}/datos.parquet", index=False)

    mltable.from_parquet_files(
        [{"file": f"{carpeta}/datos.parquet"}]).save(carpeta)

    activo = Data(
        path=carpeta,
        type=AssetTypes.MLTABLE,
        name=nombre,
        description=(f"Churn mensual, todas las bajas, horizonte de un mes. "
                     f"Base corregida entre los domingos del mes. "
                     f"Piso de {PISO} clientes."),
        version=ASSET_VERSION
    )
    creado = cliente.data.create_or_update(activo)
    print(nombre, "-", len(tabla), "renglones - version", creado.version)

Found the config file in: /config.json

CHURN_REG_T1_V02_TRAIN - ya existe la version 1 - se omite
CHURN_REG_T1_V02_TEST - ya existe la version 1 - se omite

In [9]:
# =====================================================================
# Ficha tecnica del dato: como esta construido este pronostico.
# Todo se calcula del dato, nada esta escrito a mano.
# =====================================================================
PISO       = 100
MES_CORTE  = 202603
MESES_TEST = [202604, 202605, 202606]
ULTIMO_MES = 202607

def titulo(t):
    print()
    print("=" * 78)
    print(t)
    print("=" * 78)

titulo("1. FUENTE")
print(f"Tabla      : silver.indicadores_cluster_features")
print(f"Lakehouse  : TP_MSPLogistica_Lakehouse   Workspace: Cerebro-Datos")
print(f"Renglones  : {df.shape[0]:,}")
print(f"Columnas   : {df.shape[1]}   (91 de origen mas DomingosDelMes y BaseReal, que agregamos nosotros)")
print(f"Clusteres  : {df['Cluster'].nunique():,}")
print(f"Periodos   : {df['AnioMes'].nunique()}  de {df['AnioMes'].min()} a {df['AnioMes'].max()}")

titulo("2. CORRECCION DE LA BASE DE USUARIOS")
print("La columna BaseDeUsuarios trae la suma de los cortes semanales,")
print("que se hacen en domingo. Se divide entre los domingos del mes.")
print()
dom = df.groupby("AnioMes")["DomingosDelMes"].max()
print("Meses de 5 domingos:", ", ".join(str(x) for x in dom[dom == 5].index))
print("Meses de 4 domingos:", ", ".join(str(x) for x in dom[dom == 4].index))
print()
print(f"Nota: {MES_INCOMPLETO} tiene 5 domingos en el calendario pero el archivo")
print("solo alcanzo a capturar uno. Por eso se excluye.")

titulo("3. EFECTO DE LA CORRECCION")
comp = (df[df["AnioMes"] != MES_INCOMPLETO]
        .groupby("AnioMes")
        .agg(Publicada=("BaseDeUsuarios", "sum"),
             Corregida=("BaseReal", "sum"),
             Netas=("AdicionesNetas", "sum")))
print(f"Base publicada en {ULTIMO_MES} : {comp.loc[ULTIMO_MES,'Publicada']:>14,.0f}")
print(f"Base corregida en {ULTIMO_MES} : {comp.loc[ULTIMO_MES,'Corregida']:>14,.0f}")
print(f"Factor de inflado           : {comp.loc[ULTIMO_MES,'Publicada']/comp.loc[ULTIMO_MES,'Corregida']:>14,.2f}")

titulo("4. VALIDACION DE LA CORRECCION")
primero = comp.index.min()
ultimo  = comp.index.max()
crecio  = comp.loc[ultimo, "Corregida"] - comp.loc[primero, "Corregida"]
netas   = comp.loc[comp.index > primero, "Netas"].sum()
print("Si la correccion es buena, el cambio de la base debe empatar")
print("con las altas netas registradas en el mismo periodo.")
print()
print(f"Crecimiento de la base corregida : {crecio:>12,.0f}")
print(f"Suma de adiciones netas          : {netas:>12,.0f}")
print(f"Diferencia                       : {crecio-netas:>12,.0f}   ({100*(crecio-netas)/netas:.2f}%)")

titulo("5. LA COLUMNA Churn DE LA TABLA ESTA MAL")
c = df[(df["AnioMes"] != MES_INCOMPLETO) & (df["Churn"] > 0) &
       (df["Cancelaciones"] != 0) & (df["BaseDeUsuarios"] > 0)].copy()

# La columna Churn viene como fraccion, no como porcentaje.
# El factor implicito es la base entre la que realmente divide.
c["factor"] = c["BaseDeUsuarios"] * c["Churn"] / c["Cancelaciones"].abs()

print("La columna Churn divide entre un factor fijo, sin importar")
print("cuantos domingos tuvo el mes. El factor implicito es:")
print()
print(f"Mediana del factor : {c['factor'].median():.4f}   (deberia ser 4 o 5 segun el mes)")
print(f"Minimo             : {c['factor'].min():.4f}")
print(f"Maximo             : {c['factor'].max():.4f}")
print(f"Renglones medidos  : {len(c):,}")
print()
print("4.3333 son las semanas promedio de un mes. Al usar un fijo,")
print("el churn publicado se subestima en los meses de 5 domingos")
print("y se sobrestima en los de 4.")

titulo("6. CIFRAS DE BASE Y CRECIMIENTO")
print(f"Base corregida {primero} : {comp.loc[primero,'Corregida']:>12,.0f}")
print(f"Base corregida {ultimo} : {comp.loc[ultimo,'Corregida']:>12,.0f}")
print(f"Crecimiento total        : {100*(comp.loc[ultimo,'Corregida']/comp.loc[primero,'Corregida']-1):>12.2f} %")
c26 = comp[comp.index >= 202601]
meses26 = len(c26) - 1
print(f"Ritmo 2026, mensual      : {100*((c26['Corregida'].iloc[-1]/c26['Corregida'].iloc[0])**(1/meses26)-1):>12.2f} %")
print(f"Netos por mes en 2026    : {(c26['Corregida'].iloc[-1]-c26['Corregida'].iloc[0])/meses26:>12,.0f}")

titulo("7. DEFINICIONES DE BAJA")
u = df[df["AnioMes"] == ULTIMO_MES]
tot   = abs(u["Cancelaciones"].sum())
invol = abs(u["CancelacionesInvoluntarias"].sum())
vol   = abs(u["CancelacionesVoluntarias"].sum())
base  = u["BaseReal"].sum()
print(f"Mes de referencia: {ULTIMO_MES}")
print()
print(f"Bajas totales        : {tot:>10,.0f}   churn {100*tot/base:>6.3f} %")
print(f"  Por falta de pago  : {invol:>10,.0f}   churn {100*invol/base:>6.3f} %   ({100*invol/tot:.1f}% del total)")
print(f"  Por decision       : {vol:>10,.0f}   churn {100*vol/base:>6.3f} %   ({100*vol/tot:.1f}% del total)")
print()
desc = (df["Cancelaciones"] - df["CancelacionesInvoluntarias"] - df["CancelacionesVoluntarias"]).abs().sum()
print(f"Renglones donde el desglose no cierra: {int(desc)}")
print("Las cancelaciones se guardan con signo negativo.")

titulo("8. EXCLUSIONES")
zonas_todas = largo["Cluster"].nunique()
con_piso = largo[largo["Base_M1"] >= PISO]
print(f"Periodo {MES_INCOMPLETO} excluido: solo trae un corte de cinco.")
print(f"Zonas con base en cero: excluidas.")
print()
print(f"Zonas totales            : {zonas_todas:,}")
print(f"Zonas con {PISO}+ clientes  : {con_piso['Cluster'].nunique():,}")
print(f"Zonas excluidas          : {zonas_todas - con_piso['Cluster'].nunique():,}")
print(f"Base que representan     : {100*con_piso['Base_M1'].sum()/largo['Base_M1'].sum():.2f} % se conserva")
print()
print("Las zonas excluidas son de expansion, casi todas con nombre AMPLIACION.")
print("Con menos de 100 clientes el churn como porcentaje no es medible:")
print("con 4 clientes, uno que se va son 25 puntos.")

titulo("9. CORTE DE ENTRENAMIENTO")
print("Los tres horizontes pronostican los mismos tres meses,")
print("para que sus errores sean comparables entre si.")
print()
print(f"{'Horizonte':<12}{'Entrena hasta':<16}{'Prueba con':<26}{'Pronostica'}")
for h, corte, prueba in [(1, 202603, [202604, 202605, 202606]),
                         (2, 202602, [202603, 202604, 202605]),
                         (3, 202601, [202602, 202603, 202604])]:
    print(f"{'T'+str(h):<12}{corte:<16}{str(prueba[0])+' a '+str(prueba[-1]):<26}"
          f"{prueba[0]+h} a {prueba[-1]+h}")

d = largo[(largo["Definicion"] == "Bajas totales") & (largo["Base_M1"] >= PISO)].dropna(
    subset=VARIABLES + ["Churn_T1"])
print()
print(f"Renglones de entrenamiento T1 : {len(d[d['AnioMes'] <= MES_CORTE]):,}")
print(f"Renglones de prueba T1        : {len(d[d['AnioMes'].isin(MESES_TEST)]):,}")
print(f"Zonas en el modelo T1         : {d['Cluster'].nunique():,}")

titulo("10. VARIABLES DEL MODELO")
print(f"Son {len(VARIABLES)}, todas construidas sin usar el mes que se predice:")
print()
for i, v in enumerate(VARIABLES, 1):
    print(f"  {i:>2}. {v}")

titulo("11. ALGORITMO Y METRICA")
print("Random Forest, 100 arboles, profundidad 8, semilla 42.")
print("Metrica: MAE en puntos de churn, y error porcentual como")
print("suma de errores entre suma de valores reales.")
print()
print("Data Assets en Azure ML:")
print("  CHURN_REG_T1_V02_TRAIN")
print("  CHURN_REG_T1_V02_TEST")

==============================================================================
1. FUENTE
==============================================================================
Tabla      : silver.indicadores_cluster_features
Lakehouse  : TP_MSPLogistica_Lakehouse   Workspace: Cerebro-Datos
Renglones  : 30,203
Columnas   : 93   (91 de origen mas DomingosDelMes y BaseReal, que agregamos nosotros)
Clusteres  : 1,511
Periodos   : 20  de 202501 a 202608

==============================================================================
2. CORRECCION DE LA BASE DE USUARIOS
==============================================================================
La columna BaseDeUsuarios trae la suma de los cortes semanales,
que se hacen en domingo. Se divide entre los domingos del mes.

Meses de 5 domingos: 202503, 202506, 202508, 202511, 202603, 202605, 202608
Meses de 4 domingos: 202501, 202502, 202504, 202505, 202507, 202509, 202510, 202512, 202601, 202602, 202604, 202606, 202607

Nota: 202608 tiene 5 domingos en el calendario pero el archivo
solo alcanzo a capturar uno. Por eso se excluye.

==============================================================================
3. EFECTO DE LA CORRECCION
==============================================================================
Base publicada en 202607 :     22,552,852
Base corregida en 202607 :      5,638,213
Factor de inflado           :           4.00

==============================================================================
4. VALIDACION DE LA CORRECCION
==============================================================================
Si la correccion es buena, el cambio de la base debe empatar
con las altas netas registradas en el mismo periodo.

Crecimiento de la base corregida :      472,573
Suma de adiciones netas          :      475,736
Diferencia                       :       -3,163   (-0.66%)

==============================================================================
5. LA COLUMNA Churn DE LA TABLA ESTA MAL
==============================================================================
La columna Churn divide entre un factor fijo, sin importar
cuantos domingos tuvo el mes. El factor implicito es:

Mediana del factor : 4.3334   (deberia ser 4 o 5 segun el mes)
Minimo             : 4.0410
Maximo             : 4.6668
Renglones medidos  : 25,647

4.3333 son las semanas promedio de un mes. Al usar un fijo,
el churn publicado se subestima en los meses de 5 domingos
y se sobrestima en los de 4.

==============================================================================
6. CIFRAS DE BASE Y CRECIMIENTO
==============================================================================
Base corregida 202501 :    5,165,640
Base corregida 202607 :    5,638,213
Crecimiento total        :         9.15 %
Ritmo 2026, mensual      :         0.73 %
Netos por mes en 2026    :       40,385

==============================================================================
7. DEFINICIONES DE BAJA
==============================================================================
Mes de referencia: 202607

Bajas totales        :     86,648   churn  1.537 %
  Por falta de pago  :     62,981   churn  1.117 %   (72.7% del total)
  Por decision       :     23,667   churn  0.420 %   (27.3% del total)

Renglones donde el desglose no cierra: 0
Las cancelaciones se guardan con signo negativo.

==============================================================================
8. EXCLUSIONES
==============================================================================
Periodo 202608 excluido: solo trae un corte de cinco.
Zonas con base en cero: excluidas.

Zonas totales            : 1,509
Zonas con 100+ clientes  : 1,312
Zonas excluidas          : 197
Base que representan     : 99.82 % se conserva

Las zonas excluidas son de expansion, casi todas con nombre AMPLIACION.
Con menos de 100 clientes el churn como porcentaje no es medible:
con 4 clientes, uno que se va son 25 puntos.

==============================================================================
9. CORTE DE ENTRENAMIENTO
==============================================================================
Los tres horizontes pronostican los mismos tres meses,
para que sus errores sean comparables entre si.

Horizonte   Entrena hasta   Prueba con                Pronostica
T1          202603          202604 a 202606           202605 a 202607
T2          202602          202603 a 202605           202605 a 202607
T3          202601          202602 a 202604           202605 a 202607

Renglones de entrenamiento T1 : 10,327
Renglones de prueba T1        : 3,919
Zonas en el modelo T1         : 1,311

==============================================================================
10. VARIABLES DEL MODELO
==============================================================================
Son 15, todas construidas sin usar el mes que se predice:

   1. Churn
   2. Churn_M1
   3. Churn_M2
   4. Churn_M3
   5. Churn_Prom3M
   6. Churn_Prom6M
   7. Churn_Delta1M
   8. Churn_Delta3M
   9. Churn_Delta6M
  10. Base_M1
  11. Base_Crecimiento1M
  12. Bajas_M1
  13. Instalaciones_M1
  14. Mes
  15. Trimestre

==============================================================================
11. ALGORITMO Y METRICA
==============================================================================
Random Forest, 100 arboles, profundidad 8, semilla 42.
Metrica: MAE en puntos de churn, y error porcentual como
suma de errores entre suma de valores reales.

Data Assets en Azure ML:
  CHURN_REG_T1_V02_TRAIN
  CHURN_REG_T1_V02_TEST

In [10]:
# =====================================================================
# Muestra que la base de una zona brinca con los domingos del mes,
# mientras el movimiento real de clientes es de decenas.
# =====================================================================
ZONA = "AEROPUERTO TAMPICO"

demo = df[df["Cluster"] == ZONA].sort_values("AnioMes")[
    ["AnioMes", "DomingosDelMes", "BaseDeUsuarios", "AdicionesNetas", "BaseReal"]
].copy()

demo["BrincoDeLaBase"] = demo["BaseDeUsuarios"].diff()

demo = demo.rename(columns={
    "BaseDeUsuarios":  "BasePublicada",
    "AdicionesNetas":  "ClientesRealesQueEntraron",
    "BaseReal":        "BaseCorregida",
})

demo = demo[["AnioMes", "DomingosDelMes", "BasePublicada", "BrincoDeLaBase",
             "ClientesRealesQueEntraron", "BaseCorregida"]]

demo["BaseCorregida"] = demo["BaseCorregida"].round(0)
demo.reset_index(drop=True)

,AnioMes,DomingosDelMes,BasePublicada,BrincoDeLaBase,ClientesRealesQueEntraron,BaseCorregida
0,202501,4,18266,NaN,16,4566.0
1,202502,4,18273,7.0,13,4568.0
2,202503,5,22968,4695.0,26,4594.0
3,202504,4,18427,-4541.0,-11,4607.0
4,202505,4,18452,25.0,10,4613.0
5,202506,5,23030,4578.0,28,4606.0
6,202507,4,18518,-4512.0,-9,4630.0
7,202508,5,23130,4612.0,-1,4626.0
8,202509,4,18502,-4628.0,-32,4626.0
9,202510,4,18337,-165.0,-33,4584.0
10,202511,5,22817,4480.0,-8,4563.0
11,202512,4,18311,-4506.0,24,4578.0
12,202601,4,18486,175.0,39,4622.0
13,202602,4,18581,95.0,20,4645.0
14,202603,5,23375,4794.0,43,4675.0
15,202604,4,19005,-4370.0,58,4751.0
16,202605,5,23950,4945.0,33,4790.0
17,202606,4,19360,-4590.0,36,4840.0
18,202607,4,19543,183.0,61,4886.0
19,202608,5,4872,-14671.0,2,974.0

In [11]:
# =====================================================================
# La base de una zona, mes por mes.
# =====================================================================
df[df["Cluster"] == "AEROPUERTO TAMPICO"][
    ["AnioMes", "BaseDeUsuarios", "AdicionesNetas"]
].sort_values("AnioMes")

    AnioMes  BaseDeUsuarios  AdicionesNetas
0    202501           18266              16
1    202502           18273              13
2    202503           22968              26
3    202504           18427             -11
4    202505           18452              10
5    202506           23030              28
6    202507           18518              -9
7    202508           23130              -1
8    202509           18502             -32
9    202510           18337             -33
10   202511           22817              -8
11   202512           18311              24
12   202601           18486              39
13   202602           18581              20
14   202603           23375              43
15   202604           19005              58
16   202605           23950              33
17   202606           19360              36
18   202607           19543              61
19   202608            4872               2

In [12]:
# =====================================================================
# La misma zona, dividiendo la base entre los cortes de cada mes.
# =====================================================================
ZONA = "AEROPUERTO TAMPICO"

d = df[df["Cluster"] == ZONA].sort_values("AnioMes")[
    ["AnioMes", "DomingosDelMes", "BaseDeUsuarios", "AdicionesNetas"]].copy()

# Agosto 2026 tiene 5 domingos en el calendario, pero el archivo
# solo alcanzo a capturar un corte.
d["Cortes"] = d["DomingosDelMes"]
d.loc[d["AnioMes"] == 202608, "Cortes"] = 1

d["BaseEntreCortes"] = (d["BaseDeUsuarios"] / d["Cortes"]).round(0)

d[["AnioMes", "Cortes", "BaseDeUsuarios", "BaseEntreCortes", "AdicionesNetas"]
  ].reset_index(drop=True)

    AnioMes  Cortes  BaseDeUsuarios  BaseEntreCortes  AdicionesNetas
0    202501       4           18266           4566.0              16
1    202502       4           18273           4568.0              13
2    202503       5           22968           4594.0              26
3    202504       4           18427           4607.0             -11
4    202505       4           18452           4613.0              10
5    202506       5           23030           4606.0              28
6    202507       4           18518           4630.0              -9
7    202508       5           23130           4626.0              -1
8    202509       4           18502           4626.0             -32
9    202510       4           18337           4584.0             -33
10   202511       5           22817           4563.0              -8
11   202512       4           18311           4578.0              24
12   202601       4           18486           4622.0              39
13   202602       4           18581           4645.0              20
14   202603       5           23375           4675.0              43
15   202604       4           19005           4751.0              58
16   202605       5           23950           4790.0              33
17   202606       4           19360           4840.0              36
18   202607       4           19543           4886.0              61
19   202608       1            4872           4872.0               2

In [13]:
# =====================================================================
# Que valores toma MixTV, para saber si es porcentaje o conteo.
# =====================================================================
print("Estadisticas de MixTV:")
print(df["MixTV"].describe().round(4))
print()
print("Cuantos valores distintos:", df["MixTV"].nunique())
print("Cuantos son numeros enteros:", (df["MixTV"] % 1 == 0).sum(), "de", len(df))
print()
print("Comparado con las columnas que si son conteos de instalaciones:")
print(df[["Instalaciones", "Instalaciones2P", "Instalaciones3P", "MixTV"]].head(15))

Estadisticas de MixTV:
count    27956.0000
mean         0.3854
std          0.1912
min          0.0000
25%          0.2941
50%          0.3844
75%          0.4737
max          1.0000
Name: MixTV, dtype: float64

Cuantos valores distintos: 3309
Cuantos son numeros enteros: 2911 de 30203

Comparado con las columnas que si son conteos de instalaciones:
    Instalaciones  Instalaciones2P  Instalaciones3P   MixTV
0             117          65.7540          51.2460  0.4380
1              99          53.5887          45.4113  0.4587
2             131          65.9716          65.0284  0.4964
3              82          41.4920          40.5080  0.4940
4             105          69.6990          35.3010  0.3362
5              87          46.9800          40.0200  0.4600
6             102          65.5044          36.4956  0.3578
7             116          76.7108          39.2892  0.3387
8              69          45.4158          23.5842  0.3418
9              79          51.3500          27.6500  0.3500
10             89          54.0942          34.9058  0.3922
11            112          65.1840          46.8160  0.4180
12            130          72.7220          57.2780  0.4406
13            112          63.9968          48.0032  0.4286
14            125          82.7750          42.2250  0.3378

In [1]:
# =====================================================================
# EVIDENCIA DEL ERROR EN silver.indicadores_cluster_features
#
# Celda autocontenida. No necesita nada previo: se conecta, lee la tabla
# y muestra las pruebas. Corre en unos 30 segundos.
# =====================================================================
try:
    from deltalake import DeltaTable
except ModuleNotFoundError:
    import sys, subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "deltalake"])
    from deltalake import DeltaTable

from msal import ConfidentialClientApplication
import pandas as pd

# ---- Configuracion ---------------------------------------------------
TENANT_ID     = "a8571760-3e06-487e-957e-e38e27254e02"
CLIENT_ID     = "30df81e6-980d-4a53-bf84-27a0b0c6338e"
CLIENT_SECRET = "IGN8Q~FwgNgc9UO7~zKIQ-2HVWVPQtjYn6khUajb"

FABRIC_WORKSPACE_ID = "1a3256b7-8ccf-4be6-88d0-f0338b57c58c"
LAKEHOUSE_ID        = "49804c1d-ae26-4818-beaf-0d5c96796119"

ZONA_EJEMPLO   = "AEROPUERTO TAMPICO"
MESES_EJEMPLO  = [202501, 202502, 202503, 202504]
MES_INCOMPLETO = 202608

# ---- Lectura ---------------------------------------------------------
app = ConfidentialClientApplication(
    client_id=CLIENT_ID,
    authority=f"https://login.microsoftonline.com/{TENANT_ID}",
    client_credential=CLIENT_SECRET)

tok = app.acquire_token_for_client(
    scopes=["https://onelake.fabric.microsoft.com/.default"])

if "access_token" not in tok:
    raise Exception(tok.get("error_description", tok))

df = DeltaTable(
    f"abfss://{FABRIC_WORKSPACE_ID}@onelake.dfs.fabric.microsoft.com/"
    f"{LAKEHOUSE_ID}/Files/TP_MSPLogistica_Lakehouse/silver/indicadores_cluster_features",
    storage_options={"bearer_token": tok["access_token"],
                     "use_fabric_endpoint": "true"}).to_pandas()

# ---- Domingos de cada mes -------------------------------------------
df["Fecha"] = pd.to_datetime(df["Fecha"])
meses = df[["AnioMes", "Fecha"]].drop_duplicates("AnioMes").copy()
meses["Domingos"] = meses["Fecha"].apply(
    lambda f: len(pd.date_range(f.replace(day=1),
                                f.replace(day=1) + pd.offsets.MonthEnd(0),
                                freq="W-SUN")))
df = df.merge(meses[["AnioMes", "Domingos"]], on="AnioMes", how="left")

def titulo(t):
    print()
    print("=" * 76)
    print(t)
    print("=" * 76)

titulo(f"1. EL DATO COMO ESTA HOY   -   zona {ZONA_EJEMPLO}")
e = df[(df["Cluster"] == ZONA_EJEMPLO) &
       (df["AnioMes"].isin(MESES_EJEMPLO))].sort_values("AnioMes")
print(e[["AnioMes", "Domingos", "BaseDeUsuarios", "CasasPasadas",
         "AdicionesNetas"]].to_string(index=False))

titulo("2. LOS BRINCOS NO SON CRECIMIENTO")
a, b = e.iloc[1], e.iloc[2]
print(f"De {a['AnioMes']} a {b['AnioMes']}:")
print(f"  La base brinca          : {b['BaseDeUsuarios'] - a['BaseDeUsuarios']:>10,.0f} clientes")
print(f"  Las casas pasadas brincan: {b['CasasPasadas']  - a['CasasPasadas']:>10,.0f} casas")
print(f"  Clientes que entraron    : {b['AdicionesNetas']:>10,.0f}")

titulo("3. EL BRINCO ES EXACTAMENTE 5 ENTRE 4")
print(f"  {b['CasasPasadas']:,.0f} / {a['CasasPasadas']:,.0f} = "
      f"{b['CasasPasadas']/a['CasasPasadas']:.4f}")
print(f"  5 / 4 = 1.2500")
print(f"  {b['AnioMes']} tiene {b['Domingos']} domingos, {a['AnioMes']} tiene {a['Domingos']}.")

titulo("4. AL DIVIDIR ENTRE LOS DOMINGOS, EL NUMERO SE ESTABILIZA")
e2 = e[["AnioMes", "Domingos", "BaseDeUsuarios", "CasasPasadas"]].copy()
e2["BaseReal"]  = (e2["BaseDeUsuarios"] / e2["Domingos"]).round(0)
e2["CasasReal"] = (e2["CasasPasadas"]  / e2["Domingos"]).round(0)
print(e2.to_string(index=False))
print()
print("Las casas pasadas quedan iguales los cuatro meses.")
print("Es infraestructura: no se mueve de un mes a otro.")

titulo("5. LA PENETRACION NO SE AFECTA")
r = e.iloc[0]
print(f"  Sin corregir : {r['BaseDeUsuarios']:,.0f} / {r['CasasPasadas']:,.0f} = "
      f"{100*r['BaseDeUsuarios']/r['CasasPasadas']:.2f} %")
print(f"  Corregido    : {r['BaseDeUsuarios']/r['Domingos']:,.0f} / "
      f"{r['CasasPasadas']/r['Domingos']:,.0f} = "
      f"{100*(r['BaseDeUsuarios']/r['Domingos'])/(r['CasasPasadas']/r['Domingos']):.2f} %")
print()
print("El error esta arriba y abajo, y se cancela.")

titulo("6. LA COLUMNA Churn TAMBIEN ESTA MAL, POR OTRA RAZON")
c = df[(df["AnioMes"] != MES_INCOMPLETO) & (df["Churn"] > 0) &
       (df["Cancelaciones"] != 0) & (df["BaseDeUsuarios"] > 0)].copy()
c["factor"] = c["BaseDeUsuarios"] * c["Churn"] / c["Cancelaciones"].abs()
print("No divide entre los domingos del mes: divide entre un valor fijo.")
print()
print(f"  Mediana del factor : {c['factor'].median():.4f}")
print(f"  Minimo             : {c['factor'].min():.4f}")
print(f"  Maximo             : {c['factor'].max():.4f}")
print(f"  Renglones medidos  : {len(c):,}")
print()
print("4.3333 son las semanas promedio de un mes. Nunca es 4 ni 5.")
print("Por eso el churn publicado se subestima en los meses de 5 domingos.")

titulo("7. COMPROBACION NACIONAL")
df["BaseReal"] = df["BaseDeUsuarios"] / df["Domingos"]
n = (df[df["AnioMes"] != MES_INCOMPLETO].groupby("AnioMes")
     .agg(Corregida=("BaseReal", "sum"), Netas=("AdicionesNetas", "sum")))
crecio = n["Corregida"].iloc[-1] - n["Corregida"].iloc[0]
netas  = n["Netas"].iloc[1:].sum()
print("Si la correccion es buena, el cambio de la base debe empatar")
print("con las altas netas registradas en el mismo periodo.")
print()
print(f"  Periodo                          : {n.index[0]} a {n.index[-1]}")
print(f"  Crecimiento de la base corregida : {crecio:>12,.0f}")
print(f"  Suma de adiciones netas          : {netas:>12,.0f}")
print(f"  Diferencia                       : {crecio-netas:>12,.0f}   ({100*(crecio-netas)/netas:.2f}%)")

titulo("8. MESES DE 5 DOMINGOS")
d5 = meses[meses["Domingos"] == 5]["AnioMes"].tolist()
print("  ", ", ".join(str(x) for x in d5))
print()
print(f"Nota: {MES_INCOMPLETO} aparece aqui por calendario, pero el archivo")
print("solo alcanzo a capturar un corte. Ese mes se excluye del analisis.")

============================================================================
1. EL DATO COMO ESTA HOY   -   zona AEROPUERTO TAMPICO
============================================================================
 AnioMes  Domingos  BaseDeUsuarios  CasasPasadas  AdicionesNetas
  202501         4           18266        106796              16
  202502         4           18273        106796              13
  202503         5           22968        133495              26
  202504         4           18427        106796             -11

============================================================================
2. LOS BRINCOS NO SON CRECIMIENTO
============================================================================
De 202502 a 202503:
  La base brinca          :      4,695 clientes
  Las casas pasadas brincan:     26,699 casas
  Clientes que entraron    :         26

============================================================================
3. EL BRINCO ES EXACTAMENTE 5 ENTRE 4
============================================================================
  133,495 / 106,796 = 1.2500
  5 / 4 = 1.2500
  202503 tiene 5 domingos, 202502 tiene 4.

============================================================================
4. AL DIVIDIR ENTRE LOS DOMINGOS, EL NUMERO SE ESTABILIZA
============================================================================
 AnioMes  Domingos  BaseDeUsuarios  CasasPasadas  BaseReal  CasasReal
  202501         4           18266        106796    4566.0    26699.0
  202502         4           18273        106796    4568.0    26699.0
  202503         5           22968        133495    4594.0    26699.0
  202504         4           18427        106796    4607.0    26699.0

Las casas pasadas quedan iguales los cuatro meses.
Es infraestructura: no se mueve de un mes a otro.

============================================================================
5. LA PENETRACION NO SE AFECTA
============================================================================
  Sin corregir : 18,266 / 106,796 = 17.10 %
  Corregido    : 4,566 / 26,699 = 17.10 %

El error esta arriba y abajo, y se cancela.

============================================================================
6. LA COLUMNA Churn TAMBIEN ESTA MAL, POR OTRA RAZON
============================================================================
No divide entre los domingos del mes: divide entre un valor fijo.

  Mediana del factor : 4.3334
  Minimo             : 4.0410
  Maximo             : 4.6668
  Renglones medidos  : 25,647

4.3333 son las semanas promedio de un mes. Nunca es 4 ni 5.
Por eso el churn publicado se subestima en los meses de 5 domingos.

============================================================================
7. COMPROBACION NACIONAL
============================================================================
Si la correccion es buena, el cambio de la base debe empatar
con las altas netas registradas en el mismo periodo.

  Periodo                          : 202501 a 202607
  Crecimiento de la base corregida :      472,573
  Suma de adiciones netas          :      475,736
  Diferencia                       :       -3,163   (-0.66%)

============================================================================
8. MESES DE 5 DOMINGOS
============================================================================
   202503, 202506, 202508, 202511, 202603, 202605, 202608

Nota: 202608 aparece aqui por calendario, pero el archivo
solo alcanzo a capturar un corte. Ese mes se excluye del analisis.